Repository RatikKapoor/cpsc-585, pull requests merged in 2023-03, with the labels that each got.

#27 feat: ECS system with ImGui updates
  DustRiders/DustRiders/Camera.cpp
  DustRiders/DustRiders/DustRiders.vcxproj
  DustRiders/DustRiders/DustRiders.vcxproj.filters
  DustRiders/DustRiders/ECS.cpp
  DustRiders/DustRiders/ECS.h
  DustRiders/DustRiders/Entity.h
  DustRiders/DustRiders/Ground.h
  DustRiders/DustRiders/InputHandler.h
  DustRiders/DustRiders/Overlay.cpp
  DustRiders/DustRiders/Overlay.h
  DustRiders/DustRiders/PhysicsProvider.h
  DustRiders/DustRiders/PhysicsSystem.cpp
  DustRiders/DustRiders/PhysicsSystem.h
  DustRiders/DustRiders/RenderingSystem.cpp
  DustRiders/DustRiders/Vehicle.cpp
  DustRiders/DustRiders/Vehicle.h
  DustRiders/DustRiders/Window.cpp
  DustRiders/DustRiders/main.cpp
Labels: refactor

#32 fix: Issue where nullptr when item is removed from ECS
  DustRiders/DustRiders/ECS.h
  DustRiders/DustRiders/Overlay.cpp
Labels: bug

#37 feat: Random rock generation
  DustRiders/DustRiders/Obstacle.cpp
  DustRiders/DustRiders/main.cpp
Labels: enhancement

#39 feat: AI continuous path finding
  DustRiders/DustRiders/AIVehicle.cpp
  DustRiders/DustRiders/AIVehicle.h
  DustRiders/DustRiders/main.cpp
Labels: enhancement

#40 feat: AI algorithm improvements
  DustRiders/DustRiders/AIVehicle.cpp
  DustRiders/DustRiders/Vehicle.cpp
  DustRiders/DustRiders/Vehicle.h
  DustRiders/DustRiders/main.cpp
Labels: enhancement

#42 fix: Ray gun sound correctly emits
  DustRiders/DustRiders/InputHandler.cpp
  DustRiders/DustRiders/InputHandler.h
  DustRiders/DustRiders/Overlay.cpp
  DustRiders/DustRiders/Vehicle.cpp
  DustRiders/DustRiders/main.cpp
Labels: bug

#46 chore: Organize file filters
  DustRiders/DustRiders/DustRiders.vcxproj.filters
Labels: chore

#47 feat: JSON path loading for AI cars
  DustRiders/DustRiders/AIPathHandler.h
  DustRiders/DustRiders/AIVehicle.cpp
  DustRiders/DustRiders/AIVehicle.h
  DustRiders/DustRiders/DustRiders.vcxproj
  DustRiders/DustRiders/DustRiders.vcxproj.filters
  DustRiders/DustRiders/LocationWriter.h
  DustRiders/DustRiders/Vehicle.cpp
  DustRiders/DustRiders/Vehicle.h
  DustRiders/DustRiders/assets/drivingPaths/path1.json
  DustRiders/DustRiders/assets/drivingPaths/path2.json
  DustRiders/DustRiders/assets/drivingPaths/path3.json
  DustRiders/DustRiders/main.cpp
Labels: enhancement, chore

#55 feat: Improved chunk and obstacle handling
  DustRiders/DustRiders/ChunkHandler.cpp
  DustRiders/DustRiders/ChunkHandler.h
  DustRiders/DustRiders/ObstacleHandler.cpp
  DustRiders/DustRiders/ObstacleHandler.h
  DustRiders/DustRiders/main.cpp
Labels: enhancement

#54 feat: Somewhat better vehicle handling
  DustRiders/DustRiders/ConstantsHelper.h
  DustRiders/DustRiders/Vehicle.cpp
  DustRiders/DustRiders/assets/constants.json
  DustRiders/DustRiders/media/vehicledata/Base.json
Labels: enhancement

#57 feat: Ray hit noises
  DustRiders/DustRiders/RayBeam.cpp
  DustRiders/DustRiders/RayBeam.h
  DustRiders/DustRiders/Vehicle.cpp
  DustRiders/DustRiders/Vehicle.h
  DustRiders/DustRiders/main.cpp
Labels: enhancement

#60 feat: Vehicles speed up with each map chunk
  DustRiders/DustRiders/AIVehicle.cpp
  DustRiders/DustRiders/ChunkHandler.h
  DustRiders/DustRiders/ConstantsHelper.h
  DustRiders/DustRiders/Vehicle.cpp
  DustRiders/DustRiders/Vehicle.h
  DustRiders/DustRiders/assets/constants.json
Labels: enhancement

#64 feat: AI now shoots at players and itself
  DustRiders/DustRiders/AIVehicle.cpp
  DustRiders/DustRiders/AIVehicle.h
  DustRiders/DustRiders/ConstantsHelper.h
  DustRiders/DustRiders/RayBeam.cpp
  DustRiders/DustRiders/RayBeam.h
  DustRiders/DustRiders/Vehicle.cpp
  DustRiders/DustRiders/assets/constants.json
  DustRiders/DustRiders/main.cpp
Labels: enhancement
